server.port=8081

server.servlet.session.cookie.name=SMARTSESSION
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=false
server.servlet.session.cookie.same-site=lax

smart.fhir-base-url=http://localhost:8080
smart.discovery-url=http://localhost:8080/.well-known/smart-configuration
smart.client-id=smart-client
smart.client-secret=smart-secret
smart.redirect-uri=http://localhost:8081/callback
smart.launch-patient=patient-1
smart.launch-encounter=encounter-1
